<a href="https://colab.research.google.com/github/Gatsby2997/Numpy-Practice/blob/main/Numpy_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([1, 2, 3, 4])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
 abc = np.array([[1,2],[3,4]])

In [ ]:
abc

array([[1, 2],
       [3, 4]])

In [ ]:
 a = [2,3,4]

In [ ]:
np.asarray(a)

array([2, 3, 4])

In [ ]:
ab = np.matrix(a)

In [ ]:
ab

matrix([[2, 3, 4]])

In [ ]:
 np.asanyarray(ab)

matrix([[2, 3, 4]])

In [ ]:
a = np.array(ab)

In [ ]:
 c = a

In [ ]:
print(c)

[[2 3 4]]


In [ ]:
c[0] = 100

In [ ]:
print(a)

[[100 100 100]]


In [ ]:
a[0] = 200

In [ ]:
a

array([[200, 200, 200]])

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
it = (i*i for i in range(5))

In [ ]:
np.fromiter(it,int)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.fromstring('8 9', sep=' ')

array([8., 9.])

#Numpy Data Types

In [ ]:
ls = [1,2,3,4,5,6]

In [ ]:
 ar = np.array(ls) #To change iterable object into array

In [ ]:
ar

array([1, 2, 3, 4, 5, 6])

In [ ]:
ar.ndim   #To check dimension of array

1

In [ ]:
ar2 = np.array([[1,2,3],[2,4,3]])  #To Make 2-D array

In [ ]:
ar2.ndim

2

In [ ]:
ar2.size   # How many value in array

6

In [ ]:
ar2.shape   #To show row and column data

(2, 3)

In [ ]:
ar2.dtype #To check data type in array

dtype('int64')

In [ ]:
ar22 = np.array([(1.4, 44, 34), (45, 22, 11)]) #Test how array perform with different dtype in array

In [ ]:

ar22

array([[ 1.4, 44. , 34. ],
       [45. , 22. , 11. ]])

In [ ]:
ar22.dtype

dtype('float64')

In [ ]:
range(0,5)

range(0, 5)

In [ ]:
list(range(0,5)) #range function always take parameter in integer

[0, 1, 2, 3, 4]

In [ ]:
 list(range(0.5,4))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(0.5, 5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [ ]:
np.arange(2.4,6.7,0.5)

array([2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4])

In [ ]:
np.linspace(1,5,5) #generate data with 2 or 3 parameter start, end and how many data want to generate

array([1., 2., 3., 4., 5.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
a=np.zeros((3,4,2))

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
on = np.ones((2,4,2))

In [ ]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]]])

In [ ]:
np.empty((3,5))

array([[5.00845723e-310, 0.00000000e+000, 6.58894808e-310,
        6.58894812e-310, 6.58894811e-310],
       [6.58894812e-310, 6.58894812e-310, 6.58894811e-310,
        6.58894812e-310, 6.58894812e-310],
       [6.58891651e-310, 1.63041663e-322, 5.00946812e-310,
        6.58894839e-310, 1.26480805e-321]])

In [ ]:
a =np.eye(4)

In [ ]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a[1,1]

1.0

In [ ]:
np.logspace(2,5,3, base = 2)

array([ 4.       , 11.3137085, 32.       ])

In [ ]:
c = np.random.randn(3,4)

In [ ]:
import pandas as pd

In [ ]:
a = pd.DataFrame(c)

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3 non-null      float64
 1   1       3 non-null      float64
 2   2       3 non-null      float64
 3   3       3 non-null      float64
dtypes: float64(4)
memory usage: 224.0 bytes


In [ ]:
a.describe()

0         1         2         3
count  3.000000  3.000000  3.000000  3.000000
mean   0.622517 -0.966619  0.702718 -0.010690
std    1.461243  0.724055  0.196582  1.364398
min   -1.056842 -1.543415  0.503054 -1.277726
25%    0.131885 -1.372895  0.606045 -0.732896
50%    1.320612 -1.202374  0.709035 -0.188066
75%    1.462196 -0.678221  0.802550  0.622827
max    1.603781 -0.154069  0.896065  1.433720

In [ ]:
intrand = np.random.randint(1,110, (2,3,4))

In [ ]:
intrand

array([[[ 72,  47,  50,  62],
        [ 73,  83,  27,  40],
        [ 42,  35,  63,  96]],

       [[ 33,  47, 105,  12],
        [102,  89,  55,   4],
        [ 36,  85, 108,   7]]])

In [ ]:
intrand[:,1:3,1:3]

array([[[ 83,  27],
        [ 35,  63]],

       [[ 89,  55],
        [ 85, 108]]])

In [ ]:
intrand[1,0:2,1:4]

array([[ 47, 105,  12],
       [ 89,  55,   4]])

In [ ]:
abc = np.random.randint(1,110, (3,4))

In [ ]:
abc

array([[ 17,  64,  76,  83],
       [ 77,  99,  20,  91],
       [ 73,  25,  81, 105]])

In [ ]:
pd.DataFrame(abc).to_csv("test.csv")

In [ ]:
arr = np.random.rand(3,4)

In [ ]:
arr

array([[0.0903858 , 0.80255057, 0.17172256, 0.60098277],
       [0.62704808, 0.41337308, 0.84650195, 0.11631455],
       [0.70476068, 0.0341943 , 0.31973053, 0.4954575 ]])

In [ ]:
arr1 = arr.reshape(4,3)

In [ ]:
arr1

array([[0.0903858 , 0.80255057, 0.17172256],
       [0.60098277, 0.62704808, 0.41337308],
       [0.84650195, 0.11631455, 0.70476068],
       [0.0341943 , 0.31973053, 0.4954575 ]])

In [ ]:
arr1[1,2]

0.41337307940325585

In [ ]:
arr = np.random.randint(1,100, (5,5))

In [ ]:
arr

array([[49, 40, 19, 45, 32],
       [30, 84, 54, 48, 68],
       [ 8, 89, 68, 84, 86],
       [63, 78, 71, 40, 46],
       [58, 58, 98, 38, 91]])

In [ ]:
arr>50

array([[False, False, False, False, False],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False,  True]])

In [ ]:
arr[arr>50]

array([84, 54, 68, 89, 68, 84, 86, 63, 78, 71, 58, 58, 98, 91])

In [ ]:
arr[2:4,1:3]

array([[89, 68],
       [78, 71]])

In [ ]:
arr[0][[1]]=100

In [ ]:
arr

array([[ 49, 100,  19,  45,  32],
       [ 30,  84,  54,  48,  68],
       [  8,  89,  68,  84,  86],
       [ 63,  78,  71,  40,  46],
       [ 58,  58,  98,  38,  91]])

In [ ]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [ ]:
arr1

array([[2, 1, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [1, 2, 2]])

In [ ]:
arr1 * arr2

array([[4, 2, 2],
       [1, 2, 1],
       [1, 4, 2]])

In [ ]:
arr1 @ arr2

array([[7, 9, 7],
       [5, 6, 5],
       [5, 6, 5]])

In [ ]:
arr1/0

<ipython-input-112-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# Numpy Broadcasting

In [ ]:
arr = np.zeros((4,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
row = np.array([[1,2,3,4]])

In [ ]:
row.ndim

2

In [ ]:
row

array([[1, 2, 3, 4]])

In [ ]:
x = row.T

In [ ]:
arr + x

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [ ]:
arr1 = np.random.randint(1,4, (3,4))

In [ ]:
arr1

array([[3, 1, 2, 1],
       [3, 1, 3, 2],
       [3, 3, 1, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.41421356, 1.        ],
       [1.73205081, 1.        , 1.73205081, 1.41421356],
       [1.73205081, 1.73205081, 1.        , 1.        ]])

In [ ]:
np.exp(arr1)

array([[20.08553692,  2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183, 20.08553692,  7.3890561 ],
       [20.08553692, 20.08553692,  2.71828183,  2.71828183]])

In [ ]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.30103   , 0.        ],
       [0.47712125, 0.        , 0.47712125, 0.30103   ],
       [0.47712125, 0.47712125, 0.        , 0.        ]])