<a href="https://colab.research.google.com/github/Gatsby2997/Numpy-Practice/blob/main/Numpy_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - Array Manipulation

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10, (3,4))

In [ ]:
arr

array([[2, 1, 4, 6],
       [6, 2, 8, 1],
       [6, 8, 8, 3]])

In [ ]:
arr.reshape(6,2)

array([[2, 1],
       [4, 6],
       [6, 2],
       [8, 1],
       [6, 8],
       [8, 3]])

In [ ]:
arr.reshape(2,6)

array([[2, 1, 4, 6, 6, 2],
       [8, 1, 6, 8, 8, 3]])

In [ ]:
arr.T

array([[2, 6, 6],
       [1, 2, 8],
       [4, 8, 8],
       [6, 1, 3]])

In [ ]:
arr

array([[2, 1, 4, 6],
       [6, 2, 8, 1],
       [6, 8, 8, 3]])

In [ ]:
arr.flatten()

array([2, 1, 4, 6, 6, 2, 8, 1, 6, 8, 8, 3])

In [ ]:
arr1 = np.array([1,2,3,3,4])

In [ ]:
arr1.ndim

1

In [ ]:
np.expand_dims((arr1), axis =0)

array([[1, 2, 3, 3, 4]])

In [ ]:
np.squeeze(arr)

array([[2, 1, 4, 6],
       [6, 2, 8, 1],
       [6, 8, 8, 3]])

In [ ]:
data = np.array([[1],[2],[3]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
# Numpy - Binary Operations

In [ ]:
arr2 = np.random.randint(1,10, (3,4))

In [ ]:
arr2

array([[3, 2, 9, 1],
       [9, 3, 8, 2],
       [4, 7, 6, 8]])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
arr3 = np.random.randint(1,10, (3,4))

In [ ]:
arr3

array([[3, 9, 4, 2],
       [8, 4, 6, 4],
       [6, 4, 7, 9]])

In [ ]:
-arr3

array([[-3, -9, -4, -2],
       [-8, -4, -6, -4],
       [-6, -4, -7, -9]])

In [ ]:
arr2 | arr3

array([[ 3, 11, 13,  3],
       [ 9,  7, 14,  6],
       [ 6,  7,  7,  9]])

In [ ]:
arr2>arr3

array([[False, False,  True, False],
       [ True, False,  True, False],
       [False,  True, False, False]])

In [ ]:
#Numpy - String Function

In [ ]:
np.array(['Vikash', 'Kumar'])

array(['Vikash', 'Kumar'], dtype='<U6')

In [ ]:
np.array([1,3,5, "abc"])

array(['1', '3', '5', 'abc'], dtype='<U21')

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array(['vikah', 'jaj'])

In [ ]:
b.dtype

dtype('<U5')

In [ ]:
c = np.array([1,3,5,6.7, "Vikash"])

In [ ]:
c.dtype

dtype('<U32')

In [ ]:
d =  np.array(['vikash', 'kumar', 'age'])

In [ ]:
np.char.upper(d)

array(['VIKASH', 'KUMAR', 'AGE'], dtype='<U6')

In [ ]:
np.char.title(d)

array(['Vikash', 'Kumar', 'Age'], dtype='<U6')

In [ ]:
np.char.capitalize(d)

array(['Vikash', 'Kumar', 'Age'], dtype='<U6')

In [ ]:
arr2

array([[3, 2, 9, 1],
       [9, 3, 8, 2],
       [4, 7, 6, 8]])

In [ ]:
arr3

array([[3, 9, 4, 2],
       [8, 4, 6, 4],
       [6, 4, 7, 9]])

In [ ]:
np.multiply(arr2, arr3)

array([[ 9, 18, 36,  2],
       [72, 12, 48,  8],
       [24, 28, 42, 72]])

In [ ]:
np.dot(arr2,arr3)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
arr2 * arr3

array([[ 9, 18, 36,  2],
       [72, 12, 48,  8],
       [24, 28, 42, 72]])

In [ ]:
abc = np.random.randint(1,100, (4,))

In [ ]:
abc[1]=96

In [ ]:
np.unique(abc)

array([14, 19, 96])

In [ ]:
np.concatenate(d,b)

TypeError: only integer scalar arrays can be converted to a scalar index