<a href="https://colab.research.google.com/github/Gatsby2997/Numpy-Practice/blob/main/Numpy_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Sort , Search , Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,3,5,5,6,7,4.2,7,8,22,45,77,43])

In [4]:
arr

array([ 4. ,  3. ,  5. ,  5. ,  6. ,  7. ,  4.2,  7. ,  8. , 22. , 45. ,
       77. , 43. ])

In [5]:
np.sort(arr)

array([ 3. ,  4. ,  4.2,  5. ,  5. ,  6. ,  7. ,  7. ,  8. , 22. , 43. ,
       45. , 77. ])

In [6]:
np.searchsorted(arr, 34)

10

In [7]:
arr1 = np.array([0,45,664,5,9,7,0,0])

In [8]:
np.count_nonzero(arr1)

5

In [9]:
np.where(arr > 6)

(array([ 5,  7,  8,  9, 10, 11, 12]),)

In [11]:
np.extract(arr>6, arr)

array([ 7.,  7.,  8., 22., 45., 77., 43.])